Some weights of DeiTForImageClassificationWithTeacher were not initialized from the model checkpoint at facebook/deit-base-distilled-patch16-224 and are newly initialized because the shapes did not match:
- cls_classifier.weight: found shape torch.Size([1000, 768]) in the checkpoint and torch.Size([4, 768]) in the model instantiated
- cls_classifier.bias: found shape torch.Size([1000]) in the checkpoint and torch.Size([4]) in the model instantiated
- distillation_classifier.weight: found shape torch.Size([1000, 768]) in the checkpoint and torch.Size([4, 768]) in the model instantiated
- distillation_classifier.bias: found shape torch.Size([1000]) in the checkpoint and torch.Size([4]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Loaded: (145, 145, 200) (145, 145)
Coords total=289 train=145 val=144
Tiles pre-filter: train=63 val=62
After rarity filter:
  train: {11: 18, 14: 11, 2: 8, 10: 6}
  val  : {11: 17, 2: 11, 10: 5, 14: 9}
Model label map: {'2': 0, '10': 1, '11': 2, '14': 3}
  0%|          | 0/165 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/pkadukar/furi-hsi/jobs/run_deit_t32s16_weighted_es.py", line 214, in <module>
    trainer.train()
  File "/home/pkadukar/miniconda3/envs/furi310/lib/python3.10/site-packages/transformers/trainer.py", line 2325, in train
    return inner_training_loop(
  File "/home/pkadukar/miniconda3/envs/furi310/lib/python3.10/site-packages/transformers/trainer.py", line 2674, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/home/pkadukar/miniconda3/envs/furi310/lib/python3.10/site-packages/transformers/trainer.py", line 4020, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/home/pkadukar/furi-hsi/jobs/run_deit_t32s16_weighted_es.py", line 168, in compute_loss
    labels = inputs.pop("labels")
KeyError: 'labels'
  0%|          | 0/165 [00:00<?, ?it/s]
