Some weights of the model checkpoint at facebook/deit-base-distilled-patch16-224 were not used when initializing DeiTForImageClassificationWithTeacher: ['cls_classifier.bias', 'cls_classifier.weight', 'distillation_classifier.bias', 'distillation_classifier.weight']
- This IS expected if you are initializing DeiTForImageClassificationWithTeacher from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DeiTForImageClassificationWithTeacher from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Loaded: (145, 145, 200) (145, 145)
Coords total=64 train=32 val=32
Tiles pre-filter: train=8 val=7
After rarity filter:
  train: {}
  val  : {}
Model label map: {}
Traceback (most recent call last):
  File "/home/pkadukar/furi-hsi/jobs/run_deit_t32s16_weighted_es.py", line 214, in <module>
    trainer.train()
  File "/home/pkadukar/miniconda3/envs/furi310/lib/python3.10/site-packages/transformers/trainer.py", line 2325, in train
    return inner_training_loop(
  File "/home/pkadukar/miniconda3/envs/furi310/lib/python3.10/site-packages/transformers/trainer.py", line 2375, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/home/pkadukar/miniconda3/envs/furi310/lib/python3.10/site-packages/transformers/trainer.py", line 1140, in get_train_dataloader
    return self._get_dataloader(
  File "/home/pkadukar/miniconda3/envs/furi310/lib/python3.10/site-packages/transformers/trainer.py", line 1109, in _get_dataloader
    dataloader_params["sampler"] = sampler_fn(dataset)
  File "/home/pkadukar/miniconda3/envs/furi310/lib/python3.10/site-packages/transformers/trainer.py", line 1080, in _get_train_sampler
    return RandomSampler(train_dataset)
  File "/home/pkadukar/miniconda3/envs/furi310/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 156, in __init__
    raise ValueError(
ValueError: num_samples should be a positive integer value, but got num_samples=0
